### ISSUE TITLE
checking alignment: *** caught segfault *** address (nil), cause 'memory not mapped'

### ISSUE THREAD

**Issue by drhoads** [Sudaraka88/BacGWES#4]
My first real run for ldweaver on 24 genomes
installed in WSL2Ubuntu
ran the sample set with no problems
did alignments with snippy-multi, verified.
commands at R prompt
library(LDWeaver)
setwd("/mnt/f/DNAwork/Ececorum/ldweaver_sepsis")
dset <- "ececorum_sepsis"
aln_path <- "/mnt/f/DNAwork/Ececorum/ldweaver_sepsis"
gbk_path <- system.file("extdata", "/mnt/f/DNAwork/Ececorum/prokka227/SA1.gbk", package = "LDWeaver")
LDWeaver::LDWeaver(dset = dset, aln_path = aln_path, gbk_path = gbk_path, save_additional_outputs = T)

Outputs:
##------ Sun Nov 19 05:28:41 2023 ------##

 ***** This is LDWeaver 1.3.1  *****

 Performing GWES analysis on: ececorum_sepsis  - using 20 cores

All outputs will be saved to: /mnt/f/DNAwork/Ececorum/ldweaver_sepsis/ececorum_sepsis

 *** Input paths ***

* Alignment: /mnt/f/DNAwork/Ececorum/ldweaver_sepsis
* GenBank Annotation:
* SnpEff Annotations will be performed on short-range links. SnpEff path: /home/drhoads/miniconda3/envs/r-ldweaver/lib/R/library/LDWeaver/extdata/snpEff.jar

 *** Parameters ***

Default SNP filtering: sites with gap_freq < 0.15 and non-gap minor allele freq > 0.01 will be retained.
Hamming distance calculation weight: 0.1
Links <= 20000 bp-apart will be classified as short-range (sr-links)
Approx. top 1e+06 long range links will be saved
Top sr-links with -log10(p) > 3 will be saved
Tanglegram/GWESExplorer outputs will illustrate upto: 250 top sr-links
MI Computation will use a max block size of: 10000 x 10000 SNPs! Reduce <max_blk_sz> if RAM is scarce!

~~~~~ https://github.com/Sudaraka88/LDWeaver/ ~~~~~

 #################### BLOCK 1 ####################

Parsing Alignment: /mnt/f/DNAwork/Ececorum/ldweaver_sepsis
Step 1: Checking alignment:
 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .extractAlnParam(aln_path, filter, gap_freq, maf_freq)
 2: LDWeaver::parse_fasta_alignment(aln_path = aln_path, method = snp_filt_method,     gap_freq = gap_freq, maf_freq = maf_freq)
 3: LDWeaver::LDWeaver(dset = dset, aln_path = aln_path, gbk_path = gbk_path,     save_additional_outputs = T)	

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:
***end outputs
folder was created in /mnt/f/DNAwork/Ececorum/ldweaver_sepsis/ldweaver_sepsis but it contains only an empty folder Additional_Outputs

**Comment by Sudaraka88** [comment]
Hey, thanks for using LDWeaver!

Based on the info provided, I think there is a small typo here:

aln_path <- "/mnt/f/DNAwork/Ececorum/ldweaver_sepsis"

You need to provide the path to your snippy alignment file here. It seems you have provided the name of a directory instead?

Let me know how it goes.

**Comment by drhoads** [comment]
That got the alignment loaded but then it choked reading the GBK file:

 #################### BLOCK 1 ####################

Parsing Alignment: /mnt/f/DNAwork/Ececorum/ldweaver_sepsis/core.full.aln
Step 1: Checking alignment: 2261297 bp per seq
Step 2: Extracting seq info: 47 seqs found
Step 3: Filtering SNPs: 130972 sites retained
Step 4: Building matrices: Done!
Step 5: Savings snp.dat...BLOCK 1 complete in 5.83 s


 #################### BLOCK 2 ####################

Reading the GBK file, validate_length_check =  TRUE
Error in LDWeaver::parse_genbank_file(gbk_path = gbk_path, g = snp.dat$g,  :
  Can't locate file
In addition: Warning message:
In normalizePath(gbk_path) : path[1]="": No such file or directory

## end output
my commands were:
library(LDWeaver)
setwd("/mnt/f/DNAwork/Ececorum/ldweaver_sepsis")
dset <- "ececorum_sepsis"
aln_path <- "/mnt/f/DNAwork/Ececorum/ldweaver_sepsis/core.full.aln"
gbk_path <- system.file("extdata", "/mnt/f/DNAwork/Ececorum/prokka227/SA1.gbk", package = "LDWeaver")
LDWeaver::LDWeaver(dset = dset, aln_path = aln_path, gbk_path = gbk_path, save_additional_outputs = T)

Just wondering if "extdata" is supposed to be something I set in the set for gbk_path??

**Comment by Sudaraka88** [comment]
I should have picked this earlier. Please try with:

gbk_path <- "/mnt/f/DNAwork/Ececorum/prokka227/SA1.gbk"

system.file() is only needed to access files bundled with packages, since your gbk is an external file, you don't need to use it. 

Please also ensure your gbk contains the reference genome sequence.

**Comment by drhoads** [comment]
I got that system.file() call from your github instructions.  Made it past Block 2 and now into block 5.  Will update you later.

**Comment by drhoads** [comment]
Not certain what happened. Got to the section BLOCK 5 and completed Block 97 of 105 and the gave this:
Block 97 of 105 ...... Adding 11842 LR links with MI>0.287 to file ...... Adding 425799 SR links to list ... Done in 351.92 s
Block 98 of 105 ...Killed
(r-ldweaver) drhoads@ARSC-A-G4LJXP3:~$
I know it wasn't me because I was gone and letting it run.  I have restarted.

**Comment by Sudaraka88** [comment]
It looks like your system is out of ram. How much ram do you have?

I don't think running again would help much in the same system, if you have the option to add more ram, that'll be good to try...

**Comment by drhoads** [comment]
The system has 128 GB of RAM but I will have to look at how much free RAM there was...

**Comment by drhoads** [comment]
I have another machine with 256 GB of RAM

**Comment by Sudaraka88** [comment]
Yeah, since you have 131k SNPs, it'll require a fair amount of RAM. 

Also, using an alignment with only 47 sequences is probably not going to churn out good results, if you have more data, I'd recommend pooling at least 500 genomes...

**Comment by drhoads** [comment]
I already have some key SNPs from a roary-scoary analysis. For this species there are only 227 genomes known.  The isolates I am running are polyphyletic and represent a new pathotype.  I am trying your software out based on your paper to see if the LD values for those key SNPs come out.

**Comment by Sudaraka88** [comment]
Okay, I see...

Since this method relies on accurately estimating the LD decay with base-pair separation, this usually requires a large number of genomes. If possible, it might be better to try some form of (core-genome?) alignment with all 227 genomes.

**Comment by drhoads** [comment]
What was not clear from your manuscript was how to discern LD for SNPs in a subset of the isolates.  So I was feeling my way into the software and its application.  For scoary we can input phenotypic data.

**Comment by drhoads** [comment]
So my home machine has only 30 Gb of free memory for my WSL2Ubuntu, my lab machine has 120 Gb.  So do you anticipate I can run the alignment of all 227 genomes because I have that.

**Comment by Sudaraka88** [comment]
> What was not clear from your manuscript was how to discern LD for SNPs in a subset of the isolates. So I was feeling my way into the software and its application. For scoary we can input phenotypic data.

LDWeaver currently does not have an option to subset sequences from an alignment. If you need to look at SNPs only in a subset of isolates, you will need to create a subset alignment containing those sequences (for example, you can use [seqtk](https://github.com/lh3/seqtk) with the command *subseq* to do that)

> So my home machine has only 30 Gb of free memory for my WSL2Ubuntu, my lab machine has 120 Gb. So do you anticipate I can run the alignment of all 227 genomes because I have that.

It's a bit tricky to predict exactly how much RAM you will need. I'm sure 120GB can handle a dataset with 227 genomes and 100k SNPs. I have analysed similar datasets with 32GB on my laptop.

**Comment by drhoads** [comment]
Have successfully run LDWeaver on three sets of genomes, all 227, and then two subsets.  Was moving to the next step of the manhattan plot of CDS variation and getting an error I can't interpret:
# already ran library(LDweaver)
> setwd("/mnt/f/DNAwork/Ececorum/ldweaver_sepsis")
> dset <- "GWES_sepsis"
> aln_path <- "/mnt/f/DNAwork/Ececorum/ldweaver_sepsis/core.full.aln"
> gbk_path <- "/mnt/f/DNAwork/Ececorum/prokka227/SA1.gbk"
> ncores = parallel::detectCores()
> snp.dat = LDWeaver::parse_fasta_alignment(aln_path = aln_path)
Step 1: Checking alignment: 2261297 bp per seq
Step 2: Extracting seq info: 47 seqs found
Step 3: Filtering SNPs: 130972 sites retained
Step 4: Building matrices: Done!
> gbk = LDWeaver::parse_genbank_file(gbk_path = gbk_path, g = snp.dat$g)
No exons read from genbank file. Assuming sections of CDS are full exons
No transcript features (mRNA) found, using spans of CDSs
Successfully read gbk file: /mnt/f/DNAwork/Ececorum/prokka227/SA1.gbk in 5.04 s
> cds_var = LDWeaver::estimate_variation_in_CDS(gbk = gbk, snp.dat = snp.dat,
                                             ncores = ncores,
                                             num_clusts_CDS = 3,
                                             clust_plt_path = "/mnt/f/DNAwork/Ececorum/ldweaver_sepsis/GWES_sepsis/CDS_clustering.png")
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘cds’ for signature ‘"list"’
> cds_var = LDWeaver::estimate_variation_in_CDS(gbk = gbk, snp.dat = snp.dat, ncores = ncores, num_clusts_CDS = 3, clust_plt_path = "/mnt/f/DNAwork/Ececorum/ldweaver_sepsis/GWES_sepsis/CDS_clustering.png")
**Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘cds’ for signature ‘"list"’**


# Any suggestions?
>

**Comment by Sudaraka88** [comment]
It's good to hear that you were able to run LDWeaver successfully! I'm not exactly sure what you mean by 'Manhattan plot of CDS variation'. If you ran LDWeaver, all default plots should already be created inside the relevant folders. 

The next step should be to look at the (putative) outlier links in: **Annotated_links**, and **Tophits** folders.

**Comment by drhoads** [comment]
I was following the "Detailed Workthrough using Real Data".  Finished the first run:
(LDWeaver::LDWeaver(dset = dset, 
                   aln_path = aln_path, 
                   gbk_path = gbk_path, 
                   save_additional_outputs = T)) 
as modified for my own data and then progressed to: 

ncores = parallel::detectCores()

snp.dat = LDWeaver::parse_fasta_alignment(aln_path = aln_path) # parse the alignment and extract SNPs
gbk = LDWeaver::parse_genbank_file(gbk_path = gbk_path, g = snp.dat$g) # parse the annotation
cds_var = LDWeaver::estimate_variation_in_CDS(gbk = gbk, snp.dat = snp.dat, 
                                             ncores = ncores, 
                                             num_clusts_CDS = 3, 
                                             clust_plt_path = "msch/CDS_clustering.png")

This was supposed to make the clustering graph as shown on your example comparing Diversity of CDS to genome position.  
This is where I got the error message. Now I see that the clustering .png file is in the output directory. So I don't need to re-run it unless I wanted a different number of clusters, but the code on (https://github.com/Sudaraka88/LDWeaver) may need tweaking.   
After the first module I have folders for Additional_Outputs, snpEff_data, SR_SWESExplorer, and SR_Tanglegram.  Additional_Outputs, SR_SWESExplorer, and SR_Tanglegram are empty.  I don't see any Annotated_links or Tophits folders.  What 
It appears I did not get this:
Outputs

Annotated_links/X_links_annotated.tsv - tab separated file similar to sample/X_links.tsv with additional SnpEff annotations and allele distribution information
Tophits/X_tophits.tsv - tab separated file containing the top 250 links (user modifiable with max_tophipts) . Several filters are applied to extract the top links from Annotated_links/X_links_annotated.tsv
SR_Tanglegram - folder compirising html tanglegrams to easily visualise links and the corresponding genomic regions
GWESExplorer/X_GWESExplorer - folder containing the outputs necessary to dynamically explore links using [GWESExplorer](https://github.com/jurikuronen/GWES-Explorer) (X = sr,lr).

**Comment by Sudaraka88** [comment]
The longer version in the help page is just a step-by-step way to do the same thing the one-liner does. Thanks for your suggestion to change the text there, I agree, it can be improved.

To check the issue with outputs, can you please share the code you ran (the one liner) and the last bit of output generated from LDWeaver? 

It would also be helpful to see the contents in the output folder:
At the output folder, in a terminal, can you please run `ls -lRh` and copy paste the output here. Thanks!

**Comment by drhoads** [comment]
Not certain what you mean by "the last bit of output generated from LDWeaver".  I would need to re run the analysis to get what is output to stdout.  If you mean which file in the output dir, That would be different.  I had to re-run to get the stdout info. 
The code I run at the R-prompt after conda activate r-ldweaver:
library(LDWeaver)
setwd("/mnt/f/DNAwork/Ececorum/ldweaver227")
dset <- "GWES227"
aln_path <- "/mnt/f/DNAwork/Ececorum/ldweaver227/core.full.aln"
gbk_path <- "/mnt/f/DNAwork/Ececorum/prokka227/SA1.gbk"
LDWeaver::LDWeaver(dset = dset, aln_path = aln_path, gbk_path = gbk_path, save_additional_outputs = T)

I ran the whole LDWeaver again and here is the final output to the screen.  The entire output is in LDweaver_STDOUT.txt and the file listing is in files.txt

00:00:00 Genome stats :
#-----------------------------------------------
# Genome name                : 'GWES227'
# Genome version             : 'GWES227'
# Genome ID                  : 'GWES227[0]'
# Has protein coding info    : true
# Has Tr. Support Level info : true
# Genes                      : 2221
# Protein coding genes       : 2221
#-----------------------------------------------
# Transcripts                : 2221
# Avg. transcripts per gene  : 1.00
# TSL transcripts            : 0
#-----------------------------------------------
# Checked transcripts        :
#               AA sequences :   2221 ( 100.00% )
#              DNA sequences :      0 ( 0.00% )
#-----------------------------------------------
# Protein coding transcripts : 2221
#              Length errors :      0 ( 0.00% )
#  STOP codons in CDS errors :      0 ( 0.00% )
#         START codon errors :    179 ( 8.06% )
#        STOP codon warnings :      0 ( 0.00% )
#              UTR sequences :      0 ( 0.00% )
#               Total Errors :    179 ( 8.06% )
# WARNING                    : No protein coding transcript has UTR
#-----------------------------------------------
# Cds                        : 2221
# Exons                      : 2221
# Exons with sequence        : 2221
# Exons without sequence     : 0
# Avg. exons per transcript  : 1.00
# WARNING                    : No mitochondrion chromosome found
#-----------------------------------------------
# Number of chromosomes      : 2
# Chromosomes                : Format 'chromo_name size codon_table'
#               'CP010060.1'    2261297 Standard
#               'unknown'       1       Bacterial_and_Plant_Plastid
#-----------------------------------------------

00:00:00 Predicting variants
00:00:01        10000 variants (9099 variants per second), 5695 VCF entries
00:00:02        20000 variants (9671 variants per second), 11687 VCF entries
00:00:03        30000 variants (10107 variants per second), 17355 VCF entries
00:00:04        40000 variants (10098 variants per second), 23373 VCF entries
00:00:05        50000 variants (10040 variants per second), 29520 VCF entries
00:00:06        60000 variants (10350 variants per second), 35577 VCF entries
00:00:07        70000 variants (10324 variants per second), 42004 VCF entries
00:00:08        80000 variants (10305 variants per second), 48034 VCF entries

ERRORS: Some errors were detected
Error type      Number of errors
ERROR_OUT_OF_CHROMOSOME_RANGE   56941


00:00:08 Creating summary file: snpEff_summary.html
00:00:08 Creating genes file: snpEff_genes.txt
00:00:08 done.
00:00:08 Logging
00:00:13 Checking for updates...
00:00:16 Done.
Convert VCF to table ...Done!
Adding annotations to links ...
================================================================================

 #################### BLOCK 9 ####################

Preparing Tanglegrams ... Error in hclust(dist(tophits$pos1)) : must have n >= 2 objects to cluster

[files.txt](https://github.com/Sudaraka88/LDWeaver/files/13465192/files.txt)
[LDWeaver_STDOUT.txt](https://github.com/Sudaraka88/LDWeaver/files/13465193/LDWeaver_STDOUT.txt)

**Comment by Sudaraka88** [comment]
Thanks for sending this. I can see that there is an issue with the parsed genbank file, specifically here:
ERRORS: Some errors were detected
Error type                                                          Number of errors
ERROR_OUT_OF_CHROMOSOME_RANGE   56941

SnpEff is not annotating any of the links because of this.

I have seen this happen before due to (non-standard) formatting issues  - this is really a chromosome name mismatch issue, I don't think your gbk file is wrong!

Do you also have the annotation in a GFF3 format? I'm sure your annotation software must have generated this. If so, we can try using that instead...

```
dset <- "GWES227_GFF"
aln_path <- "/mnt/f/DNAwork/Ececorum/ldweaver227/core.full.aln"
gff3_path <-  "" # add the path to your GFF3 file here
LDWeaver::LDWeaver(dset = dset, aln_path = aln_path, gff3_path = gff3_path, save_additional_outputs = T)
```

Let me know how it goes.

**Comment by drhoads** [comment]
The gff file is gff3 and the sequence is at the bottom...

> gff3_path <- "/mnt/f/DNAwork/Ececorum/prokka227/SA1.gff"
> LDWeaver::LDWeaver(dset = dset, aln_path = aln_path, gff3_path = gff3_path, save_additional_outputs = T)
Error in LDWeaver::LDWeaver(dset = dset, aln_path = aln_path, gff3_path = gff3_path,  :
  Reference fasta file must be provided for gff3 annoations
>

So what is the format for passing the .fna?  I can always delete the sequence from  SA1.gff

**Comment by Sudaraka88** [comment]
Sorry, you are right, this slipped my mind. 

In the current version of LDWeaver, when you pass a gff3 file, you also need to pass the reference sequence separately 
```
dset <- "GWES227_GFF"
aln_path <- "/mnt/f/DNAwork/Ececorum/ldweaver227/core.full.aln"
gff3_path <- "/mnt/f/DNAwork/Ececorum/prokka227/SA1.gff"
ref_fasta_path <- "" # add the path to the reference sequence here

LDWeaver::LDWeaver(dset = dset, aln_path = aln_path, gff3_path = gff3_path, ref_fasta_path = ref_fasta_path, save_additional_outputs = T)
```

Please delete the sequence from the gff file. Thanks.

**Comment by drhoads** [comment]
Run finished with no error.  I have attached the capture from stdout (STDOUT.txt) and the ls -1Rs output (files.txt)
There are no subdirectories such as SR_GWESExplorer, SR_Tanglegram, or snpEff_data, and  fewer of the .png or .tsv files in the GWES folder (7 vs 26)

[files.txt](https://github.com/Sudaraka88/LDWeaver/files/13486943/files.txt)
[stdout.txt](https://github.com/Sudaraka88/LDWeaver/files/13486945/stdout.txt)

**Comment by Sudaraka88** [comment]
Checking the output, it seems the program terminated before completion:

This is the last line:
Block 115 of 120 ...... Adding 3607 LR links with MI>0.268 to file ...... Adding 13540326 SR links to list ... Done in 354.15 s

There is no need to redo the MI calculations as you have already done them. LDWeaver can load the existing files as input.

Can you please copy paste sr_links.tsv and lr_links.tsv files from your previous folder (GWES227) into the new one (GWES). 

After that, run the same one liner you just ran. Let me know if that works...

**Comment by drhoads** [comment]
Did complete but had a bunch of Warnings about genes not found.
[files.txt](https://github.com/Sudaraka88/LDWeaver/files/13487400/files.txt)
[stdout_restart.txt](https://github.com/Sudaraka88/LDWeaver/files/13487401/stdout_restart.txt)

**Comment by Sudaraka88** [comment]
It seems to have run completely this time. Thanks for sharing this. 

Those warnings are due to SnpEff checking for gene transcripts, which are not available in the GFF3 - can be safely ignored... 

All outputs seem to be generated as well. 

Next step is to scan through the Tophits and Annotated links for interesting hits.

**Comment by drhoads** [comment]
As I had mentioned earlier I was hoping to be able to discern LR or SR interactions specific to a phenotypic trait for a small subset of the isolates.   Still working with GWES-Explorer and that author.  There are issues uploading the data for the .gff and .aln files that cause discconection from the server.  Meanwhile I have been using parsnp to identify specific SNPs that have significant odds ratio scores for the specific phenotype and then will come back to the LR and SR interactions to see if those particular genes have epistatic interactions in the entire population group.  You had indicated that I would not see anything if I just ran LDWeaver on the subset of 27 isolates with the "new" phenotype.

**Comment by Sudaraka88** [comment]
Yes, since the underlying method depends on statistical outlier calling, I don't think findings from 27 isolates are reliable.

I assume the genomic regions you are interested in were in the reference genome and these 27 isolates were a part of the dataset. If so, you might pick up some relavent/strong LD signals from the analysis you just did. 

I'm sure Juri will be able to help you more with GWESExplorer. Since it is a shiny R package, you can set it up locally. It is not very resource intensive as well - should run on your laptop...

Since the software ran at the end, I will close this issue for now, feel free to reach out if there are further issues...
